FROM openjdk:11.0.4-jre-slim-buster
MAINTAINER zkaratatar
COPY /target/readingisgood-0.0.1-SNAPSHOT.jar /opt/readingisgood-0.0.1-SNAPSHOT.jar
CMD ["java","-jar","/opt/readingisgood-0.0.1-SNAPSHOT.jar"]

#docker build -t .